name: AWS example workflow
on:
  push
env:
  AWS_REGION : "eu-central-1" 
permissions:
  id-token: write
  contents: read
jobs:
  AWSAuth:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Get Caller Identity
        run: |
          aws sts get-caller-identity
